### ISSUE TITLE
Centralize Plugin-Management // Use Github.com as Plugin-Repository

### ISSUE THREAD

**Issue by Burnett01** [Burnett01/sys-api#9]
-- Draft --
Have an **optional** command-line-interface that allows execution of various commands.
- (Optional) Centralize plugin-management (plugin install, plugin update, plugin remove)
- should be enabled by { cli: true }
- should be disabled by default

---

> **plugin install <plugin-name>**
> 
> When the user enters said command, the CLI will search Github for the plugin.
> Once found, it'll be automatically installed into one of the plugin-roots.

---

> **plugin update <plugin-name>**

---

> **plugin remove <plugin-name>**
> 
> Remove plugin

**Comment by NKITMedia** [comment]
I think it is better you create a similar platform like npmjs.com.

**Comment by Burnett01** [comment]
That would be overkill. Let's not forget that the API is not in a senior state. There are a lot of things that need to be improved. I actually don't like a centralized repository such as NPM. People should be able to fetch plugins from any location. I can see this could work with Github etc

**Comment by NKITMedia** [comment]
But how do you realize then it with "install plugin"?
